//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Djudo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionatConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChampionatConfig()
        {
            this.Sorevnovanies = new HashSet<Sorevnovanie>();
            this.UchastChamps = new HashSet<UchastChamp>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDChampionat { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<byte> AgeCategorie { get; set; }
        public string Gender { get; set; }
        public Nullable<int> IDTatami { get; set; }
        public Nullable<byte> WeightCategorie { get; set; }
    
        public virtual Championat Championat { get; set; }
        public virtual Tatami Tatami { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sorevnovanie> Sorevnovanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UchastChamp> UchastChamps { get; set; }
    }
}
