//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Djudo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DjudoEntities : DbContext
    {
        public DjudoEntities()
            : base("name=DjudoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Championat> Championats { get; set; }
        public virtual DbSet<ChampionatConfig> ChampionatConfigs { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<Sorevnovanie> Sorevnovanies { get; set; }
        public virtual DbSet<Tatami> Tatamis { get; set; }
        public virtual DbSet<UchastChamp> UchastChamps { get; set; }
        public virtual DbSet<Uchastnick> Uchastnicks { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
