//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Djudo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Score { get; set; }
        public Nullable<int> IDSorevnovanie { get; set; }
        public Nullable<int> IDUchastCamp { get; set; }
        public Nullable<double> Time { get; set; }
        public Nullable<double> WaitTime { get; set; }
    
        public virtual Sorevnovanie Sorevnovanie { get; set; }
        public virtual UchastChamp UchastChamp { get; set; }
    }
}
