//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Djudo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorevnovanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sorevnovanie()
        {
            this.Rules = new HashSet<Rule>();
        }
    
        public int ID { get; set; }
        public Nullable<int> White { get; set; }
        public Nullable<int> Red { get; set; }
        public Nullable<int> NumGroup { get; set; }
        public Nullable<byte> Winner { get; set; }
        public Nullable<int> IDChampConf { get; set; }
        public Nullable<double> TimeRound { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
    
        public virtual ChampionatConfig ChampionatConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rule> Rules { get; set; }
        public virtual UchastChamp UchastChamp { get; set; }
        public virtual UchastChamp UchastChamp1 { get; set; }
    }
}
