//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Djudo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uchastnick
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uchastnick()
        {
            this.UchastChamps = new HashSet<UchastChamp>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Birthday { get; set; }
        public string Birthtown { get; set; }
        public string Street { get; set; }
        public string Hometown { get; set; }
        public string Sportsclub { get; set; }
        public Nullable<byte> Weight_kg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UchastChamp> UchastChamps { get; set; }
    }
}
