//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Djudo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UchastChamp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UchastChamp()
        {
            this.Rules = new HashSet<Rule>();
            this.Sorevnovanies = new HashSet<Sorevnovanie>();
            this.Sorevnovanies1 = new HashSet<Sorevnovanie>();
        }
    
        public int ID { get; set; }
        public int OrderNum { get; set; }
        public int IDChampionat { get; set; }
        public int IDUchastnick { get; set; }
    
        public virtual ChampionatConfig ChampionatConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rule> Rules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sorevnovanie> Sorevnovanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sorevnovanie> Sorevnovanies1 { get; set; }
        public virtual Uchastnick Uchastnick { get; set; }
    }
}
